### PR TITLE
Readme changes

### PR DESCRIPTION
**Pull request by farkon00**
UK is mostly understood as United Kingdom, but ua is Ukraine.

Btw why you was trying to eat or drink your program in ukrainian readme :)

### CODE REVIEW

**Comment by farkon00** [comment]
Btw what about checking pr to vpm?

**Review by morrigan-plus-plus — APPROVED** [review]
What do you mean trying to eat/drink? And I'll check it in a sec!

**Comment by farkon00** [comment]
> What do you mean trying to eat/drink? And I'll check it in a sec!

Споживати is not about using thing mostly. It means consuming smth. Or just like you eat food, drink coke or using some medicine, its споживати. In your case використовувати is much better word

**Comment by morrigan-plus-plus** [comment]
Ohhhh, okay! I was looking for the word "usage" so I must've been lied to :p I should've used my own tool to look haha

**Pull request merged**
